### ISSUE TITLE
Guzzle v7 support? 

### ISSUE THREAD

**Issue by vadimcasap** [Fruitware/MaibApi#11]
any intents to update to other versions of guzzle?

**Comment by alexminza** [comment]
Especially in the light of this https://github.com/advisories/GHSA-f2wf-25xc-69c9

https://github.com/guzzle/guzzle/blob/master/UPGRADING.md

**Comment by vadimcasap** [comment]
i used an external interface to wrap all and set a small internal API and laravel can communicate with this integration so for the moment all is fine and no dependence issues,

**Comment by alexminza** [comment]
@vadimcasap care to share the code?

**Comment by vadimcasap** [comment]
so it's more like a stupid implementation: 

i put this package into public directory and set a php file to accepr requests and based on that to execute some functionality
and the endpoint for callbacks it's calling the same file with checking the data 

somehow it's like a independent package that runs inside public folder of laravel and can be called from the web 

I'm thinking to move it to a subdomain.
